### ISSUE TITLE
How can I create a new CRL?

### ISSUE THREAD

**Issue by dlangille** [ecrist/ssl-admin#3]
The CRL I created a  month ago had a 1-month expiration date.

How can I:

* create a refreshed CRL?
* have a CRL with a longer expiry date? ANSWER: modify `default_crl_days` in `openssl.conf`

My work around:

* create a new cert
* revoke it

Is a new menu option called for?

I found this around line 334:

```
print "=========> Generating new Certificate Revokation List $crl\n";
`cd $working_dir/active && openssl ca -gencrl -out $crl -config $key_config`;
```

I think the command line solution is:

```
cd /usr/local/etc/ssl-admin/active
openssl ca -gencrl -out /usr/local/etc/ssl-admin/prog/crl.pem -config /usr/local/etc/ssl-admin/openssl.conf
```

But this is perl not a shell script, that won't work. It errors out.

**Comment by ecrist** [comment]
Hrm. The command line should work. Might be a change in openssl. What version are you using?

Eric Crist

On Oct 23, 2022, at 18:17, Dan Langille ***@***.***> wrote:

﻿

The CRL I create month ago had a 1-month expiration date.

How can I:

  *   create a refreshed CRL?
  *   have a CRL with a longer expiry date? ANSWER: modify default_crl_days in openssl.conf

My work around:

  *   create a new cert
  *   revoke it

Is a new menu option called for?

I found this around line 334:

print "=========> Generating new Certificate Revokation List $crl\n";
`cd $working_dir/active && openssl ca -gencrl -out $crl -config $key_config`;


I think the command line solution is:

cd /usr/local/etc/ssl-admin/active
openssl ca -gencrl -out /usr/local/etc/ssl-admin/prog/crl.pem -config /usr/local/etc/ssl-admin/openssl.conf


But this is perl not a shell script, that won't work. It errors out.

**Comment by dlangille** [comment]
I'm using this version:

```
[dan@mydev:/usr/local/etc/ssl-admin/active] $ openssl version
OpenSSL 1.1.1o-freebsd  3 May 2022
```

This is the command and output:

```
[mydev dan /usr/local/etc/ssl-admin/active] %  openssl ca -gencrl -out ~/tmp/crl.pem -config /usr/local/etc/ssl-admin/openssl.conf
Using configuration from /usr/local/etc/ssl-admin/openssl.conf
ca: Error on line 3 of config file "/usr/local/etc/ssl-admin/openssl.conf"
34389172224:error:0E065068:configuration file routines:str_copy:variable has no value:/usr/src/crypto/openssl/crypto/conf/conf_def.c:638:line 3
```

Line three is:

```
[dan@mydev:/usr/local/etc/ssl-admin/active] $ head -3 /usr/local/etc/ssl-admin/openssl.conf
# OpenSSL Configuration File for ssl-admin

dir				= $ENV::KEY_DIR

```

**Comment by ecrist** [comment]
The manual error you got makes sense, since it's populated by the ssl-admin script.  I'll work on adding a feature.

**Comment by marcin-gryszkalis** [comment]
I’m autoupdating crl (for OpenVPN and http client-cert CA) with following script (it specifies KEY_DIR and other KEY_ vars)

```
#!/bin/sh

kdx=/usr/local/etc/ssl-admin
a=$1
kd=${a:-$kdx}

KEY_CRL_LOC=./xxx.pem \
KEY_COUNTRY=pl KEY_CN=. KEY_EMAIL=. KEY_ORG=. KEY_PROVINCE=. KEY_CITY=. \
KEY_SIZE=4096 KEY_DAYS=365 \
KEY_DIR=$kd \
openssl ca -gencrl -out $kd/prog/crl.pem -config $kd/openssl.conf

# kill -HUP `cat /var/run/spoon/proxy.pid`
```

**Comment by dlangille** [comment]
> I’m autoupdating crl (for OpenVPN and http client-cert CA) with following script (it specifies KEY_DIR and other KEY_ vars)
> 
> ```
> #!/bin/sh
> 
> kdx=/usr/local/etc/ssl-admin
> a=$1
> kd=${a:-$kdx}
> 
> KEY_CRL_LOC=./xxx.pem \
> KEY_COUNTRY=pl KEY_CN=. KEY_EMAIL=. KEY_ORG=. KEY_PROVINCE=. KEY_CITY=. \
> KEY_SIZE=4096 KEY_DAYS=365 \
> KEY_DIR=$kd \
> openssl ca -gencrl -out $kd/prog/crl.pem -config $kd/openssl.conf
> 
> # kill -HUP `cat /var/run/spoon/proxy.pid`
> ```

What I would love is a script which uses the existing values in `/usr/local/etc/ssl-admin/ssl-admin.conf` - then I don't have to keep them in sync. The variables shown above are defined in that file. (e.g. `KEY_COUNTRY`, `KEY_CN`, etc).

**Comment by marcin-gryszkalis** [comment]
@dlangille One could do it, but it's not really needed as the values are ignored, they are just to make openssl.conf work - without them openssl bails out on `default_days                    = $ENV::KEY_DAYS` etc.

CRL file contains only serial numbers of revoked certs and it's signed by CA.

**Comment by dlangille** [comment]
> @dlangille One could do it, but it's not really needed as the values are ignored, they are just to make openssl.conf work - without them openssl bails out on `default_days = $ENV::KEY_DAYS` etc.
> 
> CRL file contains only serial numbers of revoked certs and it's signed by CA.

Oh. I had assumed I needed to fill in values and your script was partially redacted. Interesting.

**Comment by ecrist** [comment]
This feature is in 1.3.0 which has a release pending.  The prompt option is 'C' to generate a new CRL.  Will also add command line option so this can run via cron.
